title:              "Community Creativity 4 Development"
email:              info@cc4duganda.org
description:        "Connecting communities while finding solutions to protect the environment from global warming."
author:             CC4D
url:                "cc4d.tech"

# Social Profiles
twitter_username:   comcreative4d
github_username:    
facebook_username:  "CC4D.tech"
instagram_username:  
linkedin_username:   "Community Creativity for Development (CC4D)"
youtube_username:    "@comcreative4d"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# theme:              jekyll-theme-clean-blog
remote_theme:       https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll
markdown:           kramdown

# Collections configurations
collections:
  blog:
    output:         true
    permalink:      "/blog/:path/"
  projects:
    output:         true
    permalink:      "/projects/:path/"

# Pagination Settings
pagination:
  enabled:          true 
  per_page:         5 
  permalink:        "/page:num/"
  sort_field:       "date"
  sort_reverse:     true

# paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  # - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-remote-theme
